# Generated by Django 5.2.4 on 2025-07-18 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=60, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("image_url", models.ImageField(blank=True, null=True, upload_to="ads/", verbose_name="Изображение")),
                ("category", models.CharField(max_length=20, verbose_name="Категория")),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "новый"),
                            ("used", "б/у"),
                            ("display", "витринный"),
                            ("discounted", "уцененный"),
                            ("refurbished", "восстановленный"),
                            ("incomplete", "недоукомплектованный"),
                            ("expiring", "заканчивается срок годности"),
                            ("returned", "продается повторно"),
                            ("other", "другое"),
                        ],
                        max_length=11,
                        verbose_name="Состояние",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[("waiting", "ожидает"), ("accepted", "принята"), ("declined", "отклонена")],
                        default="waiting",
                        max_length=8,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "ad_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiving",
                        to="ads.ad",
                        verbose_name="Получение",
                    ),
                ),
                (
                    "ad_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sending",
                        to="ads.ad",
                        verbose_name="Отправление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение",
                "verbose_name_plural": "Предложения",
                "ordering": ["created_at"],
            },
        ),
    ]
